### ISSUE TITLE
Server Response 가 forward, backward 패킷보다 빠르게 도착해 redirection이 이루어지지 않음

### ISSUE THREAD

**Issue by kunheekimkr** [kunheekimkr/tcp-block#1]
![capture](https://github.com/kunheekimkr/tcp-block/assets/80766653/5446a7ad-137e-4f88-ab75-a65b39d37a21)

**Comment by snoopspy** [comment]
https://github.com/kunheekimkr/tcp-block/commit/f6dd891112491826472e8ee1458bf294704dc22f#r115422030

**Comment by kunheekimkr** [comment]
d0fb7f7

**Comment by snoopspy** [comment]
You'd better close this issue. :)
